@echo off

SET GAME_NAME=tap2top
SET OUTPUT_PATH=%PROJ_DIR%\bin
SET PROJ_DIR=%CD%
SET ANDROID_HOME=D:\DevTools\android-sdk-windows
SET ANDROID_TOOL_PATH=%ANDROID_HOME%\tools
SET ANDROID_TOOL=%ANDROID_TOOL_PATH%\android
SET JAVA_HOME=D:\DevTools\jdk1.6.0
set JARSIGNER=%JAVA_HOME%\bin\jarsigner.exe
set KEY_STORE=VGP